import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("TG2fever_dataset.csv")
plt.style.use('ggplot')

# Graph 1: Previous Medication Distribution (PIE CHART)
plt.figure(figsize=(7,7))
df["Previous_Medication"].value_counts().plot(
    kind="pie",
    autopct='%1.1f%%',
    startangle=90)

plt.title("Previous Medication Distribution")
plt.ylabel("")
plt.show()

#Implemented by Leen 
#Includes:
#Graph 2: Age distribution
#Graph 3: Age vs heart rate 

# Graph 2: Age Distribution (Histogram)
plt.figure(figsize=(9, 6))

df["Age"].plot(
    kind="hist",
    bins=10,
    color="#6c5ce7",
    edgecolor="white",
    linewidth=1.2,
    rwidth=0.9,
    alpha=0.85
)
plt.title("Age Distribution of Patients", fontsize=14, fontweight='bold', pad=15)
plt.xlabel("Age", fontsize=12)
plt.ylabel("Frequency (Number of Patients)", fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.3)
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.tight_layout()
plt.show()



# Graph 3: Age vs Heart Rate (LINE GRAPH)
sorted_df = df.sort_values(by="Age")
plt.figure(figsize=(8,5))
plt.plot(sorted_df["Age"], sorted_df["Heart_Rate"],
         marker='o',
         linewidth=3,
         color='#e74c3c')

plt.title("Age vs Heart Rate")
plt.xlabel("Age")
plt.ylabel("Heart Rate")
plt.grid(True)
plt.show()


#This part was implemented by Nooran
#includes :
#graph 4, 
#graph 5


# Figure 4: Fever Severity Levels
# This figure is designed to visualize how frequently each fever severity category appears in the dataset.
plt.figure(figsize=(8,5))  # Create a new figure window with a suitable size to make the chart clear and readable.

df["Fever_Severity"].value_counts().plot(  # Count the number of occurrences for each fever severity category, then prepare it for plotting.
    kind="barh",  # Use a horizontal bar chart because it makes category names easier to read and compare visually.
    color=['#ff7675','#fdcb6e','#55efc4'])  # Apply custom colors to make the categories visually distinct and improve presentation quality.

plt.title("Fever Severity Levels")  # Add a title to clearly describe what this graph is showing.
plt.xlabel("Count")  # Label the x-axis to indicate that it represents the number of records or patients.
plt.ylabel("Severity")  # Label the y-axis to indicate that it contains the fever severity categories.
plt.show()  # Display the completed graph to the user.



# Figure 5: Heart Rate by Fever Severity (Styled Box Plot)
# This figure is created to compare heart rate distribution across different fever severity groups.
box = df.boxplot(  # Generate a box plot from the dataset for grouped statistical comparison.
    column="Heart_Rate",  # Select the Heart_Rate column as the numerical variable to be analyzed.
    by="Fever_Severity",  # Group the heart rate values according to fever severity categories.
    patch_artist=True,  # Enable colored filling inside the boxes to improve the visual appearance of the plot.
    boxprops=dict(linewidth=2),  # Increase the thickness of the box borders so they appear more clearly.
    medianprops=dict(color='#d63031', linewidth=3),  # Highlight the median line using a stronger color and thicker width for emphasis.
    whiskerprops=dict(linewidth=2),  # Make the whisker lines thicker for clearer visibility.
    capprops=dict(linewidth=2)  # Make the cap lines at the ends of whiskers thicker for a more polished result.
)

colors = ['#74b9ff', '#55efc4', '#ffeaa7', '#ff7675', '#a29bfe']  # Create a list of colors to style the box plot categories.
for patch, color in zip(box.artists, colors):  # Loop through each box in the chart and assign a color to it.
    patch.set_facecolor(color)  # Fill each box with its corresponding color to improve distinction between groups.

plt.title("Heart Rate Distribution by Fever Severity", fontsize=15, fontweight="bold")  # Add a bold and descriptive title to explain the graph clearly.
plt.suptitle("")  # Remove the automatic extra title generated by pandas to keep the chart cleaner.
plt.xlabel("Fever Severity")  # Label the x-axis to show that each box belongs to a fever severity category.
plt.ylabel("Heart Rate")  # Label the y-axis to show that the measured values represent heart rate.
plt.grid(True, linestyle='--', alpha=0.5)  # Add a light dashed grid to make the graph easier to read and interpret.
plt.show()  # Display the final styled box plot to the user



# Function to open a new window for each graph
def open_graph_window(fig_num):
    # Stop if the dataset was not loaded
    if df is None:
        show_text("Dataset not loaded.")
        return

    # Show written output for each figure
    if fig_num == 1:
        show_text("Figure 1 opened successfully.\nPie chart for Previous Medication was generated.")
    elif fig_num == 2:
        show_text("Figure 2 opened successfully.\nHistogram for Age Distribution was generated.")
    elif fig_num == 3:
        show_text("Figure 3 opened successfully.\nLine graph for Age vs Heart Rate was generated.")
    elif fig_num == 4:
        show_text("Figure 4 opened successfully.\nBar chart for Fever Severity was generated.")
    elif fig_num == 5:
        show_text("Figure 5 opened successfully.\nBox plot for Heart Rate by Fever Severity was generated.")

    
    win = tk.Toplevel(root)
    win.title(f"Figure {fig_num}")
    win.geometry("750x650")

